CREATE DATABASE SUPPLY_CHAIN_DB;


CREATE SCHEMA SUPPLY_CHAIN_DB.RAW;
CREATE SCHEMA SUPPLY_CHAIN_DB.CURATED;
CREATE SCHEMA SUPPLY_CHAIN_DB.SEMANTIC;

SELECT *
FROM SUPPLY_CHAIN_DB.RAW.PRODUCT
LIMIT 10;

